"""Pydantic schemas for AuditLog endpoints."""

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field


class AuditLogCreate(BaseModel):
    """Explicit audit log entry (most are auto-generated by middleware)."""
    user_id: str | None = None
    action: str
    resource_type: str | None = None
    resource_id: str | None = None
    details: str | None = None
    ip_address: str | None = None
    success: bool = True


class AuditLogResponse(BaseModel):
    id: int
    user_id: str | None
    action: str
    resource_type: str | None
    resource_id: str | None
    details: str | None
    ip_address: str | None
    user_agent: str | None
    timestamp: datetime | None
    success: bool

    model_config = ConfigDict(from_attributes=True)


class AuditLogFilter(BaseModel):
    """Query parameters for filtering audit logs."""
    user_id: str | None = None
    action: str | None = None
    resource_type: str | None = None
    start_time: datetime | None = None
    end_time: datetime | None = None
    limit: int = Field(default=100, ge=1, le=1000)
    offset: int = Field(default=0, ge=0)
